/** Italian labels for published Eurostat COFOG level-II groups (gov_10a_exp). */
export const EUROSTAT_COFOG_DETAIL_LABELS = {
  GF0101: "Organi esecutivi e legislativi, affari finanziari e fiscali, affari esteri",
  GF0102: "Aiuti economici all’estero",
  GF0103: "Servizi generali",
  GF0104: "Ricerca di base",
  GF0105: "R&S nei servizi generali",
  GF0106: "Altri servizi generali",
  GF0107: "Operazioni sul debito pubblico",
  GF0108: "Trasferimenti generali tra livelli di governo",
  GF0201: "Difesa militare",
  GF0202: "Difesa civile",
  GF0203: "Aiuti militari all’estero",
  GF0204: "R&S Difesa",
  GF0205: "Altre spese per la difesa",
  GF0301: "Servizi di polizia",
  GF0302: "Servizi antincendio",
  GF0303: "Tribunali",
  GF0304: "Carceri",
  GF0305: "R&S Ordine pubblico e sicurezza",
  GF0306: "Altre spese per ordine pubblico e sicurezza",
  GF0401: "Affari economici, commerciali e del lavoro in generale",
  GF0402: "Agricoltura, silvicoltura, pesca e caccia",
  GF0403: "Combustibili ed energia",
  GF0404: "Industria estrattiva, manifatturiera e costruzioni",
  GF0405: "Trasporti",
  GF0406: "Comunicazioni",
  GF0407: "Altri settori",
  GF0408: "R&S Affari economici",
  GF0409: "Altri affari economici",
  GF0501: "Gestione dei rifiuti",
  GF0502: "Gestione delle acque reflue",
  GF0503: "Riduzione dell’inquinamento",
  GF0504: "Protezione della biodiversità e del paesaggio",
  GF0505: "R&S Protezione dell’ambiente",
  GF0506: "Altre spese per la protezione dell’ambiente",
  GF0601: "Abitazioni",
  GF0602: "Assetto territoriale",
  GF0603: "Approvvigionamento idrico",
  GF0604: "Illuminazione stradale",
  GF0605: "R&S Abitazioni e assetto territoriale",
  GF0606: "Altre spese per abitazioni e assetto territoriale",
  GF0701: "Prodotti, apparecchi e attrezzature medicali",
  GF0702: "Servizi ambulatoriali",
  GF0703: "Servizi ospedalieri",
  GF0704: "Servizi di sanità pubblica",
  GF0705: "R&S Sanità",
  GF0706: "Altre spese per la sanità",
  GF0801: "Servizi ricreativi e sportivi",
  GF0802: "Servizi culturali",
  GF0803: "Radiodiffusione ed editoria",
  GF0804: "Servizi religiosi e altre comunità",
  GF0805: "R&S Ricreazione, cultura e culto",
  GF0806: "Altre spese per ricreazione, cultura e culto",
  GF0901: "Istruzione prescolastica e primaria",
  GF0902: "Istruzione secondaria",
  GF0903: "Istruzione post-secondaria non terziaria",
  GF0904: "Istruzione terziaria",
  GF0905: "Istruzione non definibile per livello",
  GF0906: "Servizi ausiliari all’istruzione",
  GF0907: "R&S Istruzione",
  GF0908: "Altre spese per l’istruzione",
  GF1001: "Malattia e invalidità",
  GF1002: "Vecchiaia",
  GF1003: "Superstiti",
  GF1004: "Famiglia e figli",
  GF1005: "Disoccupazione",
  GF1006: "Abitazione",
  GF1007: "Esclusione sociale non classificata altrove",
  GF1008: "R&S Protezione sociale",
  GF1009: "Altre spese per la protezione sociale",
} as const;

export type EurostatCofogDetailLabelCode = keyof typeof EUROSTAT_COFOG_DETAIL_LABELS;

export function shareOfParentBasisPoints(numerator: number, denominator: number): number {
  if (denominator <= 0) {
    throw new Error("Denominatore COFOG non valido per la quota sul parent.");
  }
  return Number((BigInt(numerator) * BigInt(10_000) + BigInt(denominator) / BigInt(2)) / BigInt(denominator));
}
