export const GOVERNMENT_CITIZEN_INDICATORS = [
  {
    id: "real-household-income",
    area: "Potere d’acquisto",
    label: "Reddito reale disponibile per abitante",
    question: "Dopo imposte, contributi e inflazione, quanto resta davvero alle famiglie?",
    role: "score",
    source: "Eurostat · nasa_10_ki",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/nasa_10_ki/default/table?lang=it",
  },
  {
    id: "essential-costs",
    area: "Potere d’acquisto",
    label: "Costo delle spese essenziali",
    question: "Quanto sono aumentati cibo, energia e abitazione rispetto ai redditi?",
    role: "score",
    source: "Eurostat · prc_hicp_aind",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/prc_hicp_aind/default/table?lang=it",
  },
  {
    id: "employment-rate",
    area: "Lavoro",
    label: "Occupazione 20-64 anni",
    question: "Quante persone in età da lavoro hanno effettivamente un’occupazione?",
    role: "score",
    source: "Eurostat · lfsi_emp_a",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/lfsi_emp_a/default/table?lang=it",
  },
  {
    id: "household-saving-rate",
    area: "Risparmio",
    label: "Tasso di risparmio delle famiglie",
    question: "Quale quota del reddito non viene assorbita dai consumi correnti?",
    role: "score",
    source: "Eurostat · tec00131",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/tec00131/default/table?lang=it",
  },
  {
    id: "housing-overburden",
    area: "Casa e famiglia",
    label: "Peso eccessivo dei costi abitativi",
    question: "Quante persone spendono almeno il 40% del reddito disponibile per la casa?",
    role: "score",
    source: "Eurostat · ilc_lvho07a",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/ilc_lvho07a/default/table?lang=it",
  },
  {
    id: "neet",
    area: "Opportunità",
    label: "Giovani NEET 15-29 anni",
    question: "Quanti giovani sono fuori sia dal lavoro sia da istruzione e formazione?",
    role: "score",
    source: "Eurostat · edat_lfse_20",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/edat_lfse_20/default/table?lang=it",
  },
  {
    id: "labour-productivity",
    area: "Capacità futura",
    label: "Produttività reale per ora lavorata",
    question: "Il Paese produce più valore per ogni ora di lavoro, senza basarsi solo su più ore?",
    role: "score",
    source: "Eurostat · nama_10_lp_ulc",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/nama_10_lp_ulc/default/table?lang=it",
  },
  {
    id: "fertility",
    area: "Demografia",
    label: "Fecondità e natalità",
    question: "Le condizioni consentono alle famiglie di realizzare i propri progetti di figli?",
    role: "diagnostic",
    source: "Eurostat · demo_find",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/demo_find/default/table?lang=it",
  },
  {
    id: "graduate-migration",
    area: "Capitale umano",
    label: "Saldo migratorio dei giovani laureati",
    question: "Quanti laureati italiani di 25-34 anni partono e quanti rientrano?",
    role: "diagnostic",
    source: "Istat · trasferimenti di residenza, tavola 13",
    sourceUrl: "https://demo.istat.it/tavole/?l=it&t=apr4",
  },
  {
    id: "household-wealth",
    area: "Risparmio e rischio",
    label: "Ricchezza netta e capacità d’investire",
    question: "Come cambiano patrimonio, debiti e attività finanziarie lungo la distribuzione?",
    role: "diagnostic",
    source: "Banca d’Italia · conti distributivi",
    sourceUrl: "https://www.bancaditalia.it/statistiche/tematiche/conti-patrimoniali/conti-distributivi/",
  },
] as const;

export const GOVERNMENT_CONTEXT_GUARDRAILS = [
  "debito, interessi e costo di rifinanziamento dello Stato",
  "credito, banche e trasmissione dei tassi a famiglie e imprese",
  "dipendenza energetica, commercio estero e shock geopolitici",
  "investimenti pubblici e privati, ricerca e incentivi strategici",
] as const;
