export const GOVERNMENT_CITIZEN_INDICATORS = [
  {
    id: "real-household-income",
    area: "Potere d’acquisto",
    label: "Reddito reale disponibile per abitante",
    question: "Dopo imposte, contributi e inflazione, quanto resta davvero alle famiglie?",
    role: "score",
    exclusionReason: "La serie trimestrale è completa dal 2002 per Italia e peer, ma deve ancora essere collegata agli endpoint dei mandati e sottoposta ai test sulle revisioni.",
    source: "Eurostat · nasq_10_ki",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/nasq_10_ki/default/table?lang=it",
  },
  {
    id: "essential-costs",
    area: "Potere d’acquisto",
    label: "Costo delle spese essenziali",
    question: "Quanto sono aumentati cibo, energia e abitazione rispetto ai redditi?",
    role: "score",
    exclusionReason: "Serve fissare un paniere essenziale unico e impedire che la stessa inflazione venga contata due volte insieme al reddito reale.",
    source: "Eurostat · prc_hicp_aind",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/prc_hicp_aind/default/table?lang=it",
  },
  {
    id: "employment-rate",
    area: "Lavoro",
    label: "Occupazione 20-64 anni",
    question: "Quante persone in età da lavoro hanno effettivamente un’occupazione?",
    role: "score",
    exclusionReason: "Va armonizzata la serie trimestrale storica e va evitato il doppio conteggio con la disoccupazione già presente nel Core.",
    source: "Eurostat · lfsi_emp_a",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/lfsi_emp_a/default/table?lang=it",
  },
  {
    id: "household-saving-rate",
    area: "Risparmio",
    label: "Tasso di risparmio delle famiglie",
    question: "Quale quota del reddito non viene assorbita dai consumi correnti?",
    role: "diagnostic",
    exclusionReason: "Non ha un verso univoco: può salire per maggiore sicurezza economica oppure perché famiglie prudenti riducono i consumi durante una crisi.",
    source: "Eurostat · nasq_10_ki",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/nasq_10_ki/default/table?lang=it",
  },
  {
    id: "housing-overburden",
    area: "Casa e famiglia",
    label: "Peso eccessivo dei costi abitativi",
    question: "Quante persone spendono almeno il 40% del reddito disponibile per la casa?",
    role: "score",
    exclusionReason: "È un dato annuale e ritardato, con discontinuità d’indagine: non consente ancora aggiornamenti omogenei per tutti i governi.",
    source: "Eurostat · ilc_lvho07a",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/ilc_lvho07a/default/table?lang=it",
  },
  {
    id: "neet",
    area: "Opportunità",
    label: "Giovani NEET 15-29 anni",
    question: "Quanti giovani sono fuori sia dal lavoro sia da istruzione e formazione?",
    role: "score",
    exclusionReason: "Il dataset scelto è annuale e arriva in ritardo; una variante trimestrale va prima verificata per copertura e rotture di serie.",
    source: "Eurostat · edat_lfse_20",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/edat_lfse_20/default/table?lang=it",
  },
  {
    id: "labour-productivity",
    area: "Capacità futura",
    label: "Produttività reale per ora lavorata",
    question: "Il Paese produce più valore per ogni ora di lavoro, senza basarsi solo su più ore?",
    role: "score",
    exclusionReason: "Va scelta una sola serie comparabile nel tempo e separato il suo contributo da PIL e investimenti, per non premiare due volte lo stesso fenomeno.",
    source: "Eurostat · nama_10_lp_ulc",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/nama_10_lp_ulc/default/table?lang=it",
  },
  {
    id: "fertility",
    area: "Demografia",
    label: "Fecondità e natalità",
    question: "Le condizioni consentono alle famiglie di realizzare i propri progetti di figli?",
    role: "diagnostic",
    exclusionReason: "È annuale, reagisce con anni di ritardo e dipende anche da fattori non economici: utile come esito sociale, debole per attribuire un voto diretto.",
    source: "Eurostat · demo_find",
    sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/demo_find/default/table?lang=it",
  },
  {
    id: "graduate-migration",
    area: "Capitale umano",
    label: "Saldo migratorio dei giovani laureati",
    question: "Quanti laureati italiani di 25-34 anni partono e quanti rientrano?",
    role: "diagnostic",
    exclusionReason: "La fonte italiana non offre ancora un confronto omogeneo con i peer e partenze o rientri possono riflettere decisioni prese molti anni prima.",
    source: "Istat · trasferimenti di residenza, tavola 13",
    sourceUrl: "https://demo.istat.it/tavole/?l=it&t=apr4",
  },
  {
    id: "household-wealth",
    area: "Risparmio e rischio",
    label: "Ricchezza netta e capacità d’investire",
    question: "Come cambiano patrimonio, debiti e attività finanziarie lungo la distribuzione?",
    role: "diagnostic",
    exclusionReason: "I conti distributivi sono trimestrali ma recenti, stimati e soggetti a revisione: non coprono in modo equivalente i governi dal 1995.",
    source: "Banca d’Italia · conti distributivi",
    sourceUrl: "https://www.bancaditalia.it/statistiche/tematiche/conti-patrimoniali/conti-distributivi/",
  },
] as const;

export const GOVERNMENT_CONTEXT_GUARDRAILS = [
  "debito, interessi e costo di rifinanziamento dello Stato",
  "credito, banche e trasmissione dei tassi a famiglie e imprese",
  "dipendenza energetica, commercio estero e shock geopolitici",
  "investimenti pubblici e privati, ricerca e incentivi strategici",
] as const;
