import { MEF_IRPEF_SOURCE } from "@/lib/data/mef-irpef-source";
import { PNRR_CHILDCARE_SOURCE } from "@/lib/data/pnrr-childcare-source";

export type PublicSource = {
  slug: string;
  name: string;
  owner: string;
  area: string;
  cadence: string;
  coverage: string;
  format: string;
  url: string;
  note: string;
  joinKeys?: string[];
};

export const publicSources: PublicSource[] = [
  {
    slug: "ameco",
    name: "Commissione europea · AMECO",
    owner: "Commissione europea · DG ECFIN",
    area: "Pagella macroeconomica annuale dei governi",
    cadence: "Due release previsive principali l’anno",
    coverage: "Italia, Francia, Germania e Spagna; serie 1960-2027, Core comparabile dal 1995",
    format: "ZIP · CSV · snapshot JSON verificato",
    url: "https://economy-finance.ec.europa.eu/economic-research-and-databases/economic-databases/ameco-database/download-annual-data-set-macro-economic-database-ameco_en",
    note: "Sei indicatori alimentano il Core annuale: osservazioni fino al 2024 e previsioni 2025-2027 restano separate. L’ultimo vintage può revisionare anche la storia e non identifica effetti causali dei governi.",
    joinKeys: ["codice serie AMECO", "paese", "anno"],
  },
  {
    slug: "governi-presidenza",
    name: "Presidenza della Repubblica · giuramenti dei governi",
    owner: "Presidenza della Repubblica",
    area: "Cronologia istituzionale dei governi italiani",
    cadence: "A ogni cambio di governo",
    coverage: "Diciassette giuramenti verificati dal 1995; archivio storico e nomine del Presidente Mattarella",
    format: "PDF e pagine istituzionali · registro JSON verificato",
    url: "https://www.quirinale.it/it/pagine/nomine-presidente-sergio-mattarella",
    note: "La pagella inizia dal giuramento e usa il giuramento del successore come fine esclusiva. Il registro cita per ogni governo la pagina o la riga dell’archivio del Quirinale.",
    joinKeys: ["governo", "data del giuramento", "data del giuramento del successore"],
  },
  {
    slug: "bancaditalia",
    name: "Banca d'Italia · debito pubblico",
    owner: "Banca d'Italia",
    area: "Debito lordo della Pubblica amministrazione",
    cadence: "Mensile, con circa 45 giorni di ritardo atteso",
    coverage: "Stock, flussi, strumenti, detentori e vita residua",
    format: "BDS · ZIP · CSV · snapshot JSON verificato",
    url: "https://www.bancaditalia.it/pubblicazioni/finanza-pubblica/index.html",
    note: "Quattro cubi BDS alimentano uno snapshot versionato e riconciliato. Stock e flussi hanno significati e periodi distinti; i dati recenti possono essere rivisti.",
    joinKeys: ["ID serie BDS", "mese"],
  },
  {
    slug: "eurostat",
    name: "Eurostat · gov_10a_main",
    owner: "Eurostat",
    area: "Interessi e spesa pubblica totale",
    cadence: "Annuale",
    coverage: "Italia, ultimi cinque anni comuni per D41PAY e TE",
    format: "Statistics API · JSON-stat · snapshot JSON verificato",
    url: "https://ec.europa.eu/eurostat/databrowser/view/gov_10a_main/default/table?lang=en",
    note: "La quota degli interessi sulla spesa totale è una derivazione aritmetica, non una previsione né l'attribuzione di un effetto a un singolo servizio.",
    joinKeys: ["anno", "na_item"],
  },
  {
    slug: "eurostat-hicp",
    name: "Eurostat · IPCA mensile",
    owner: "Eurostat",
    area: "Prezzi al consumo armonizzati",
    cadence: "Mensile",
    coverage: "Italia, Francia, Germania e Spagna dal 2022; indice e variazione annua per totale, alimentari e abitazione-energia",
    format: "Statistics API · JSON-stat · snapshot JSON verificato",
    url: "https://ec.europa.eu/eurostat/databrowser/view/prc_hicp_minr/default/table?lang=en",
    note: "L'IPCA descrive i prezzi osservati e non attribuisce causalmente il loro andamento a un governo. Indice e variazione annua mantengono unità distinte.",
    joinKeys: ["periodo", "geo", "coicop18", "unità"],
  },
  {
    slug: "eurostat-cofog",
    name: "Eurostat · spesa pubblica per funzione (COFOG)",
    owner: "Eurostat (Commissione europea)",
    area: "Spesa delle Amministrazioni pubbliche per funzione",
    cadence: "Annuale; rilascio verificato del 21 luglio 2026",
    coverage:
      "UE27, area euro e 30 Stati, 2014–2024; totale e dieci divisioni COFOG in milioni di euro e in quota di PIL",
    format: "Statistics API · JSON-stat · snapshot JSON verificato",
    url: "https://ec.europa.eu/eurostat/databrowser/view/gov_10a_exp/default/table?lang=en",
    note: "Competenza economica SEC 2010, non pagamenti di cassa: non è confrontabile con SIOPE né sommabile alle missioni del bilancio dello Stato. La ripartizione per funzione non misura efficienza o qualità del servizio. Le celle con flag «b» segnano una interruzione della serie storica.",
    joinKeys: ["geo", "anno", "funzione COFOG", "unità"],
  },
  {
    slug: "istat-cofog",
    name: "ISTAT · consumi finali della PA per funzione (COFOG)",
    owner: "ISTAT — Istituto nazionale di statistica",
    area: "Consumi finali delle Amministrazioni pubbliche per funzione",
    cadence: "Annuale, con edizioni di revisione; edizione fissata 2025M12",
    coverage:
      "Italia, ripartizioni e regioni, 1995–2023; totale e dieci divisioni COFOG a prezzi correnti",
    format: "SDMX-CSV 1.0.0 · snapshot JSON verificato",
    url: "https://esploradati.istat.it/databrowser/",
    note: "Sono i consumi finali (P3) delle AP, non la spesa pubblica totale: nel 2023 valgono circa 383 miliardi contro i circa 1149 della spesa totale. Non è confrontabile con Eurostat COFOG né con SIOPE. Le aree composite contengono già le loro parti. Il dato territoriale è territorio di erogazione contabile, non «quanto riceve» un cittadino.",
    joinKeys: ["territorio", "anno", "funzione COFOG", "edizione"],
  },
  {
    slug: "istat-epea",
    name: "ISTAT · spesa per la protezione dell'ambiente (EPEA)",
    owner: "ISTAT — Istituto nazionale di statistica",
    area: "Conti della spesa per la protezione dell'ambiente",
    cadence: "Annuale, con edizioni di revisione; edizione fissata 2025M2",
    coverage:
      "Italia, 2016–2022; settori istituzionali e classi CEPA a prezzi correnti",
    format: "SDMX-CSV 1.0.0 · snapshot JSON verificato",
    url: "https://esploradati.istat.it/databrowser/",
    note: "Contabilità SEC di competenza, non cassa SIOPE. Non confrontabile in silenzio con RGS, PNRR Missione 2 o SAD/SAF. TOT_CEPA e totali settoriali non vanno sommati alle parti. Edizione 2025M2 fissata.",
    joinKeys: ["settore istituzionale", "classe CEPA", "anno", "edizione"],
  },
  {
    slug: "inps-naspi",
    name: "INPS · NASpI beneficiari e trattamenti",
    owner: "INPS — Istituto Nazionale della Previdenza Sociale",
    area: "Indennità di disoccupazione NASpI",
    cadence: "Annuale; nove package SDMX verificati, preparati dalla fonte il 2024-12-17",
    coverage:
      "Italia per ripartizioni, regioni e province, 2018–2022; beneficiari e trattamenti per sesso, classe di età e durata teorica",
    format: "SDMX-ML 2.1 · snapshot JSON verificato",
    url: "https://opendata.inps.it/opendata",
    note: "Beneficiari e trattamenti sono misure diverse — persone contro periodi di prestazione — e non vanno sommate. Sono conteggi, non euro: nessun confronto con la spesa per prestazioni o con SIOPE. È un flusso annuale, non lo stock di pensioni. Le celle soppresse per privacy restano nulle e non diventano zero.",
    joinKeys: ["territorio", "anno", "sesso", "classe di età", "durata teorica"],
  },
  {
    slug: "siope",
    name: "SIOPE / SIOPE+",
    owner: "RGS · Banca d'Italia",
    area: "Incassi e pagamenti PA",
    cadence: "Controllo orario dei file; aggiornamento quando cambia la fonte",
    coverage: "Adapter attivo: pagamenti di cassa dei Comuni",
    format: "ZIP · CSV · classificazioni contabili",
    url: "https://www.siope.it/documenti/siope2/open/last/",
    note: "Fonte primaria attiva: movimenti mensili nazionali, anagrafiche SIOPE, snapshot comunale versionato e dashboard territoriale.",
  },
  {
    slug: "istat",
    name: "ISTAT SITUAS",
    owner: "Istituto nazionale di statistica",
    area: "Dimensione e caratteristiche dei territori",
    cadence: "Quadri territoriali interrogabili per data",
    coverage: "Comuni italiani 2022–2026: superficie, popolazione e classificazioni territoriali",
    format: "API JSON · snapshot verificato",
    url: "https://situas.istat.it/web/#/territorio",
    note: "Denominatori territoriali per €/km² e contesto geografico; i fattori restano separati e non formano un indice di efficienza.",
    joinKeys: ["codice ISTAT Comune", "codice fiscale Comune", "anno"],
  },
  {
    slug: "istat-casellario-pensioni",
    name: "ISTAT · Casellario dei pensionati",
    owner: "Istituto nazionale di statistica",
    area: "Pensioni e pensionati",
    cadence: "Annuale; ultimo periodo verificato 2022",
    coverage: "Italia, 2012–2022; prestazioni pensionistiche e pensionati in due flussi distinti",
    format: "SDMX-CSV · snapshot JSON verificato",
    url: "https://esploradati.istat.it/",
    note: "I due dataflow ISTAT restano separati: pensioni misura prestazioni, pensionati misura persone. Gli importi sono lordi e non sono sommabili ai dati INPS di invalidità civile; la licenza della risposta SDMX resta non dichiarata finché non è provata dalla fonte.",
    joinKeys: ["dataflow ISTAT", "anno", "categoria"],
  },
  {
    slug: "consip",
    name: "Consip · open data acquisti",
    owner: "Consip S.p.A. (società del MEF)",
    area: "Acquisti centralizzati della PA",
    cadence: "Annuale; file verificati aggiornati dalla fonte a marzo 2026",
    coverage: "Italia, 2024–2026; ordini su Convenzioni e MEPA aggregati per regione e tipologia di amministrazione",
    format: "CSV per package CKAN · snapshot JSON verificato",
    url: "https://dati.consip.it/",
    note: "Gli importi pubblicati sono limiti inferiori: la fonte sopprime i valori in molte celle e pubblica anche storni negativi. Ordinato Consip non è un pagamento e non copre gli acquisti fuori dal Programma.",
    joinKeys: ["anno", "regione PA", "tipologia amministrazione"],
  },
  {
    slug: "openbdap",
    name: "OpenBDAP",
    owner: "Ragioneria Generale dello Stato",
    area: "Bilancio, spesa, SIOPE, opere, PNRR",
    cadence: "Variabile per dataset; pagamenti Stato mensili e consuntivi annuali",
    coverage: "Pagamenti dello Stato, opere pubbliche per CUP e Conto Economico SSN 2024",
    format: "CKAN API · OData · CSV · open data",
    url: "https://bdap-opendata.rgs.mef.gov.it/content/api",
    note: "Connettore attivo: pagamenti dello Stato, dataset MOP, snapshot del Conto Economico consuntivo 2024 degli enti SSN con voci contabili, costi del personale e servizi, e serie storica dello stanziamento enacted per missione della Legge di Bilancio (dal 2017, tassonomia stabile).",
    joinKeys: ["CUP", "codice fiscale titolare", "codice ente RGS"],
  },
  {
    slug: "anac",
    name: "BDNCP / dati aperti ANAC",
    owner: "Autorità Nazionale Anticorruzione",
    area: "Contratti pubblici e ciclo di vita degli appalti",
    cadence: "Mensile per gli open data; endpoint OCDS documentati; Analytics settimanale",
    coverage: "Snapshot CIG 2025 verificato e catalogo ufficiale collegato",
    format: "CSV · JSON · OCDS · API",
    url: "https://dati.anticorruzione.it/opendata/dataset",
    note: "Il MCP espone aggregati verificati della replica CIG 2025 con copertura, hash e limiti. La ricerca live per singolo CIG richiede ancora un indice persistente dedicato.",
    joinKeys: ["CIG", "OCID", "codice fiscale stazione appaltante", "CUP"],
  },
  {
    slug: "inps",
    name: "INPS · pensioni e invalidità civile",
    owner: "Istituto Nazionale della Previdenza Sociale",
    area: "Pensioni erogate dall'INPS e prestazioni di invalidità civile",
    cadence: "Secondo pubblicazione di osservatori, rendiconti e analisi statistiche",
    coverage: "Pensioni vigenti al 1 gennaio 2026 e serie 2012-2026; spesa invalidità civile 2021-2025 e nuove pensioni per 18 regioni 2016-2024",
    format: "Osservatori statistici · PDF istituzionali · snapshot JSON verificato",
    url: "https://www.inps.it/it/it/dati-e-bilanci.html",
    note: "Lo stock delle pensioni INPS, le liquidazioni dell'anno, la tavola per decorrenza e l'invalidità civile restano misure e perimetri distinti. Non si sommano al Casellario ISTAT. I dati pubblici verificati non consentono attribuzioni individuali.",
    joinKeys: ["regione", "anno"],
  },
  {
    slug: "cpt",
    name: "Conti Pubblici Territoriali",
    owner: "Dipartimento per le Politiche di Coesione e per il Sud",
    area: "Entrate e spese pubbliche territorializzate",
    cadence: "Annuale; serie consolidata disponibile 2000-2023",
    coverage: "21 unità territoriali CPT, perimetro Pubblica Amministrazione consolidata",
    format: "CSV · XLSX · snapshot JSON verificato",
    url: "https://politichecoesione.governo.it/it/politica-di-coesione/misurazione-valutazione-e-trasparenza/la-misurazione-delle-politiche-di-coesione/conti-pubblici-territoriali-cpt/i-dati/catalogo-open-cpt/",
    note: "Entrate e spese derivano dalla stessa release e base di cassa. Il saldo è una differenza contabile territorializzata, non una misura di merito né il residuo fiscale di Banca d'Italia.",
    joinKeys: ["codice territorio CPT", "anno"],
  },
  {
    slug: MEF_IRPEF_SOURCE.id,
    name: MEF_IRPEF_SOURCE.public.name,
    owner: MEF_IRPEF_SOURCE.owner,
    area: MEF_IRPEF_SOURCE.public.area,
    cadence: MEF_IRPEF_SOURCE.public.cadence,
    coverage: MEF_IRPEF_SOURCE.public.coverage,
    format: MEF_IRPEF_SOURCE.public.format,
    url: MEF_IRPEF_SOURCE.sourceUrl,
    note: MEF_IRPEF_SOURCE.public.note,
    joinKeys: [...MEF_IRPEF_SOURCE.public.joinKeys],
  },
  {
    slug: "ipa",
    name: "Indice PA (IPA)",
    owner: "AgID",
    area: "Anagrafe degli enti",
    cadence: "Giornaliera",
    coverage: "PA, gestori di servizi pubblici e altri soggetti censiti",
    format: "JSON · XLSX · Data API",
    url: "https://www.indicepa.gov.it/ipa-dati/dataset/enti",
    note: "Connettore attivo: ricerca enti, pagina canonica per Codice IPA, API normalizzata e aggregazioni reali.",
    joinKeys: ["Codice IPA", "codice fiscale", "codice ISTAT"],
  },
  {
    slug: "ipa-struttura",
    name: "IPA · UO e AOO",
    owner: "AgID",
    area: "Articolazioni interne e protocolli",
    cadence: "Giornaliera",
    coverage: "Unità Organizzative e Aree Organizzative Omogenee degli enti IPA",
    format: "CKAN Data API · XLSX · JSON",
    url: "https://www.indicepa.gov.it/ipa-dati/dataset/unita-organizzative",
    note: "Connettore attivo nelle schede ente: UO, relazioni padre-figlio dichiarate da IPA e AOO. Non sostituisce i regolamenti di organizzazione dei singoli enti.",
    joinKeys: ["Codice IPA", "Codice UO", "Codice AOO"],
  },
  {
    slug: "opencoesione",
    name: "OpenCoesione",
    owner: "Dipartimento per le Politiche di Coesione",
    area: "Progetti e pagamenti di coesione",
    cadence: "Bimestrale prevista per i principali dataset",
    coverage: "Aggregato nazionale per stati, temi e nature",
    format: "API · CSV · open data",
    url: "https://opencoesione.gov.it/it/opendata/",
    note: "Dashboard nazionale attiva; nessun drill-down per progetto, soggetto o territorio. Aggiornamento automatico dall'API ufficiale.",
  },
  {
    slug: PNRR_CHILDCARE_SOURCE.id,
    name: PNRR_CHILDCARE_SOURCE.public.name,
    owner: PNRR_CHILDCARE_SOURCE.owner,
    area: PNRR_CHILDCARE_SOURCE.public.area,
    cadence: PNRR_CHILDCARE_SOURCE.public.cadence,
    coverage: PNRR_CHILDCARE_SOURCE.public.coverage,
    format: PNRR_CHILDCARE_SOURCE.public.format,
    url: PNRR_CHILDCARE_SOURCE.sourceUrl,
    note: PNRR_CHILDCARE_SOURCE.public.note,
    joinKeys: [...PNRR_CHILDCARE_SOURCE.public.joinKeys],
  },
  {
    slug: "opencivitas",
    name: "OpenCivitas",
    owner: "Sogei",
    area: "Spesa e fabbisogni standard dei Comuni",
    cadence: "Irregolare; verifica del rilascio 2022 ogni 24 ore",
    coverage: "6.557 Comuni delle Regioni a statuto ordinario, annualità 2022",
    format: "ZIP · CSV · XLSX",
    url: "https://www.opencivitas.it/it/open-data",
    note: "Confronto comunale attivo tra spesa storica e spesa standard, con valori per abitante e livello dei servizi. La differenza non viene presentata come spreco.",
    joinKeys: ["codice ISTAT Comune"],
  },
  {
    slug: "partecipazioni-pubbliche",
    name: "Censimento partecipazioni pubbliche",
    owner: "MEF · Dipartimento dell'Economia",
    area: "Società partecipate e rapporti di partecipazione",
    cadence: "Rilevazione annuale",
    coverage: "Partecipazioni dichiarate dalle amministrazioni e società partecipate",
    format: "Open data elaborabile · rilevazioni annuali",
    url: "https://www.de.mef.gov.it/it/attivita_istituzionali/partecipazioni_pubbliche/open_data_partecipazioni/index.html",
    note: "Snapshot nazionale attivo: 53.656 relazioni della rilevazione 2023, aggregati e organizzazioni dichiarate da più amministrazioni. Il drill-down completo per singola relazione richiede il successivo indice persistente.",
    joinKeys: ["codice fiscale amministrazione", "codice fiscale società"],
  },
  {
    slug: "consulenti",
    name: "Consulenti Pubblici",
    owner: "Dipartimento della Funzione Pubblica",
    area: "Consulenze e incarichi",
    cadence: "Aggiornamento per singolo incarico; controllo della piattaforma ogni 6 ore",
    coverage: "Statistiche nazionali annuali per consulenti esterni e incarichi ai dipendenti PA",
    format: "API JSON · export open data",
    url: "https://consulentipubblici.dfp.gov.it/progetto",
    note: "Snapshot nazionale attivo dal 2023: incarichi, somme erogate comunicate, incarichi conclusi e principali ripartizioni. L'anno corrente è parziale e può cambiare con nuove comunicazioni.",
  },
  {
    slug: "camera",
    name: "Camera Trasparente",
    owner: "Camera dei deputati",
    area: "Parlamento",
    cadence: "Secondo pubblicazione istituzionale",
    coverage: "Bilancio e amministrazione della Camera",
    format: "Web · documenti",
    url: "https://trasparenza.camera.it/bilancio-della-camera",
    note: "Conto consuntivo 2025 e bilancio 2026 collegati ai documenti ufficiali. Gli importi strutturati conservano la precisione verificata disponibile e il significato contabile della Camera; la UI arrotonda soltanto la presentazione.",
  },
  {
    slug: "senato",
    name: "Senato · Spese e trasparenza",
    owner: "Senato della Repubblica",
    area: "Parlamento",
    cadence: "Secondo pubblicazione istituzionale",
    coverage: "Documenti contabili censiti; importi non ancora verificati",
    format: "Web · PDF",
    url: "https://www.senato.it/relazioni-con-i-cittadini/spese-trasparenza/spese-e-trasparenza",
    note: "Il rendiconto 2024 e il bilancio 2025 sono registrati come metadati ufficiali. I PDF contabili non ereditano la licenza CC BY del portale dati.senato.it e nessun importo viene pubblicato senza acquisizione, hash e parsing verificato.",
  },
  {
    slug: "pcm",
    name: "Bilanci della Presidenza del Consiglio",
    owner: "Presidenza del Consiglio dei ministri",
    area: "Palazzo Chigi",
    cadence: "Annuale, secondo approvazione e pubblicazione istituzionale",
    coverage: "Rendiconto finanziario PCM 2024, 572 righe e 13 missioni",
    format: "XLSX · snapshot JSON verificato",
    url: "https://presidenza.governo.it/AmministrazioneTrasparente/Bilanci/BilancioPreventivoConsultivo/ContoFinanziario/2024/index.html",
    note: "Impegni, pagamenti in conto competenza e pagamenti in conto residui restano separati. Il workbook è della sola PCM e non viene sommato ai Ministeri o al Parlamento. La pagina non dichiara una licenza per il file.",
  },
];

export const sourceCounts = {
  total: publicSources.length,
};
