import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { launchBrowser, closeBrowser, defaultBaseUrl } from './harness.mjs';

const browser=await launchBrowser();
const base=defaultBaseUrl();
mkdirSync('artifacts/browser',{recursive:true});
try {
  for(const width of [320,390,768,1280]) {
    const page=await browser.newPage();
    const errors=[],requests=[];
    let hold=false,held;
    page.on('pageerror',error=>errors.push(error.message));
    await page.setViewport({width,height:width<600?844:900});
    await page.setRequestInterception(true);
    const answer={ok:true,kind:'ai_answer',provider:'openai',model:'gpt-4.1-mini',text:'## Totale\n\n**Risposta di prova**: <b>testo semplice</b>\n\n- Periodo 2025\n- Fonte ufficiale',evidence:[{dataset:'siope_comuni',title:'Pagamenti dei Comuni',sources:[{name:'SIOPE',url:'https://www.siope.it/',period:'2025'}]}]};
    const fulfill=request=>request.respond({status:200,contentType:'text/event-stream',body:[{type:'delta',text:answer.text.slice(0,16)},{type:'delta',text:answer.text.slice(16)},{type:'done',response:answer}].map(event=>`data: ${JSON.stringify(event)}\n\n`).join('')});
    page.on('request',request=>{
      if(new URL(request.url()).pathname!=='/api/assistant/chat'){void request.continue();return;}
      requests.push({headers:request.headers(),body:JSON.parse(request.postData())});
      if(hold){held=request;return;}
      void fulfill(request);
    });
    await page.goto(new URL('/assistente/anteprima',base).href,{waitUntil:'networkidle0'});
    assert.equal(new URL(page.url()).pathname,'/assistente');
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copiedText=text;}}}));
    const field='#assistant-prompt';
    const click=label=>page.click(`button[aria-label="${label}"]`);
    const replace=async(selector,value)=>{await page.$eval(selector,el=>{el.focus();el.select();});await page.keyboard.press('Backspace');await page.type(selector,value);};
    const complete=async count=>{await page.waitForFunction(count=>document.querySelectorAll('[data-assistant-reply] a[href="https://www.siope.it/"]').length===count && !document.querySelector('button[aria-label="Interrompi ricerca"]'),{},count);await page.waitForFunction(()=>!document.getAnimations().some(animation=>animation.playState==='running'));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));};
    await page.waitForSelector(field);
    assert.ok(await page.$eval('body',el=>el.scrollWidth<=innerWidth),`${width}: overflow`);
    assert.equal(await page.$$eval('button[aria-label*="scura"]',els=>els.length),0);
    await page.screenshot({path:`artifacts/browser/assistant-chat-${width}-light.png`,fullPage:true});
    await page.type(field,'@');await page.waitForSelector('[role="listbox"]');
    await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
    assert.match(await page.$eval(field,el=>el.value),/Calabria/);assert.equal(requests.length,0);
    await page.keyboard.press('Enter');await page.waitForSelector('dialog[open]');
    assert.equal(requests.length,0,'no key, no provider call');
    const selectGeometry=await page.$eval('#assistant-provider',el=>{const field=el.getBoundingClientRect(),icon=el.parentElement.querySelector('svg').getBoundingClientRect();return{center:Math.abs(field.top+field.height/2-icon.top-icon.height/2),right:field.right-icon.right,padding:parseFloat(getComputedStyle(el).paddingRight)};});
    assert.ok(selectGeometry.center<1 && selectGeometry.right>=12 && selectGeometry.right<=16 && selectGeometry.padding>=40,JSON.stringify(selectGeometry));
    await page.type('#assistant-api-key','test-only-router-key-123');
    await page.select('#assistant-provider','openai');
    assert.equal(await page.$eval('#assistant-api-key',el=>el.value),'');
    assert.equal(await page.$eval('#assistant-model',el=>el.value),'gpt-4.1-mini');
    await page.type('#assistant-api-key','test-only-openai-key-123');
    await page.click('button[type="submit"]::-p-text(Usa in questa scheda)');
    await page.waitForSelector('dialog [role="alert"]');assert.equal(requests.length,0);
    await page.click('dialog input[type="checkbox"]');
    const geometry=await page.$eval('dialog[open]',el=>{const r=el.getBoundingClientRect();return{left:r.left,right:r.right,width:innerWidth,overflow:el.scrollWidth-el.clientWidth};});
    assert.ok(geometry.left>=0&&geometry.right<=geometry.width&&geometry.overflow<=1);
    await page.screenshot({path:`artifacts/browser/assistant-chat-${width}-settings.png`,fullPage:true});
    await page.click('button[type="submit"]::-p-text(Usa in questa scheda)');
    await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')?.startsWith('Impostazioni AI:'));
    assert.equal(requests.length,0,'saving must not call provider');
    await replace(field,'Quanto hanno speso i Comuni nel 2025?');await page.keyboard.press('Enter');await complete(1);
    assert.equal(requests[0].headers.authorization,'Bearer test-only-openai-key-123');
    assert.equal(requests[0].headers.accept,'text/event-stream');
    assert.equal(JSON.stringify(requests[0].body).includes('test-only-openai-key-123'),false);
    assert.equal(requests[0].body.consent,true);
    assert.equal(await page.$$eval('[data-assistant-reply] b',els=>els.length),0);
    assert.equal(await page.$$eval('[data-assistant-reply] strong',els=>els.length),2);
    await click('Copia risposta');
    await page.waitForFunction(()=>typeof window.__copiedText==='string');
    assert.equal(await page.evaluate(()=>window.__copiedText.split('\n').at(-1)), 'SIOPE: https://www.siope.it/');
    await click('Copia domanda');
    assert.equal(await page.evaluate(()=>window.__copiedText),'Quanto hanno speso i Comuni nel 2025?');
    await page.type(field,'E nel 2024?');await page.keyboard.press('Enter');await complete(2);
    assert.deepEqual(requests[1].body.messages.map(message=>message.role),['user','assistant','user']);
    await (await page.$$('button[aria-label="Rigenera risposta"]')).at(-1).click();await complete(2);
    assert.equal(requests.length,3);assert.equal(requests[2].body.messages.at(-1).content,'E nel 2024?');
    await (await page.$$('button[aria-label="Modifica domanda"]'))[0].click();
    await replace('[id^="edit-message-"]','Quanto hanno speso i Comuni nel 2024?');
    await page.click('button::-p-text(Invia modifica)');await complete(1);
    assert.equal(requests.length,4);assert.equal(requests[3].body.messages.length,1);
    assert.equal(await page.$$eval('[data-assistant-reply]',els=>els.length),1,'edit removes downstream conversation');
    await click('Modifica domanda');await page.click('button::-p-text(Annulla modifica)');
    assert.equal(requests.length,4);
    hold=true;await page.type(field,'Domanda da interrompere');await page.keyboard.press('Enter');
    await page.waitForSelector('button[aria-label="Interrompi ricerca"]');await click('Interrompi ricerca');
    hold=false;if(held)await fulfill(held).catch(()=>{});
    await page.waitForFunction(()=>document.body.innerText.includes('Ricerca interrotta.'));
    assert.equal(await page.$$eval('[data-assistant-reply] a[href="https://www.siope.it/"]',els=>els.length),1);
    await page.screenshot({path:`artifacts/browser/assistant-chat-${width}-conversation.png`,fullPage:true});
    const composer=await page.$eval(field,el=>{const r=el.closest('form').getBoundingClientRect();return{bottom:r.bottom,viewport:innerHeight,overflow:document.body.scrollWidth-innerWidth};});
    assert.ok(composer.bottom<=composer.viewport&&composer.viewport-composer.bottom<130,`${width}: composer not docked`);
    assert.ok(composer.overflow<=1);
    await click('Nuova chat');assert.equal(await page.$$eval('[data-assistant-reply]',els=>els.length),0);
    assert.ok(await page.$('button[aria-label^="Impostazioni AI:"]'));
    await page.click('button[aria-label^="Impostazioni AI:"]');await page.click('button::-p-text(Scollega e rimuovi chiave)');
    await page.waitForSelector('button[aria-label="Collega la tua AI"]');
    await click('Collega la tua AI');assert.equal(await page.$eval('#assistant-api-key',el=>el.value),'');
    await page.select('#assistant-provider','anthropic');await page.type('#assistant-api-key','test-only-anthropic-key-123');
    await page.click('dialog input[type="checkbox"]');await page.click('button[type="submit"]::-p-text(Usa in questa scheda)');
    await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));
    await page.waitForSelector('button[aria-label="Collega la tua AI"]');await click('Collega la tua AI');
    assert.equal(await page.$eval('#assistant-api-key',el=>el.value),'');
    await page.type('#assistant-api-key','test-only-unsaved-key-123');await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));
    await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await page.reload({waitUntil:'networkidle0'});
    await click('Collega la tua AI');assert.equal(await page.$eval('#assistant-api-key',el=>el.value),'');
    assert.equal(await page.evaluate(()=>[...Object.values(localStorage),...Object.values(sessionStorage)].some(value=>value.includes('test-only-'))),false);
    await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Collega la tua AI');
    assert.deepEqual(errors,[]);await page.close();
    console.log(`PASS assistant ${width}px: key consent, sources, streaming protocol, copy, edit, regenerate, stop, context, docked composer, new chat, disconnect, pagehide, reload`);
  }
} finally {await closeBrowser(browser);}
